#!/usr/bin/env bash
#
# Build other logos from a common svg source
#
set -euf -o pipefail

insvg=$1
outdir=$2
IFS=', ' read -r -a colors_to_use_array <<< "${3:-red,green,purple,orange,yellow,black}"

# Primary colours from brand guide
COLORS=(
  "red:#ff1245"
  "green:#00a818"
  "purple:#3e10af"
  "orange:#ff7f00"
  "yellow:#ffda00"
  "black:#1b1d1e"
)

for color in "${COLORS[@]}" ; do
  color_name="${color%%:*}"
  hex="${color##*:}"

  for color_to_use in "${colors_to_use_array[@]}" ; do
    if [ "$color_name" = "$color_to_use" ] ; then
      outsvg=${outdir}/$(basename ${insvg} .svg)-${color_name}.svg
      sed s/"#000"/"${hex}"/g "${insvg}" > "${outsvg}"
    fi
  done
done
