#!/usr/bin/env bash
#
# Build other logos from a common svg source
#
set -euf -o pipefail

svg=$1
dir=$2

heights=( 16 32 64 128 256 512)
for height in "${heights[@]}"
do
  png=${dir}/$(basename ${dir})-${height}.png
  rsvg-convert --keep-aspect-ratio --height ${height} --format png --output ${png} ${svg}
done
