#!/usr/bin/env bash
#
# Create a copy of an SVG, replacing the "token" color (`#000`) with
# a colour from the brand guide.
#
# Usage:
#   create-color-copies SVG DIR COLORLIST
#
set -euf -o pipefail

insvg=$1
outdir=$2
IFS=',' read -r -a colors_to_use_array <<< "${3}"

# Primary colours from brand guide
COLORS=(
  "red:#ff1245"
  "green:#00a818"
  "purple:#3e10af"
  "orange:#ff7f00"
  "yellow:#ffda00"
  "black:#1b1d1e"
  "white:#ffffff"
  "grey:#65696B"
)

for color in "${COLORS[@]}" ; do
  color_name="${color%%:*}"
  hex="${color##*:}"

  for color_to_use in "${colors_to_use_array[@]}" ; do
    if [ "$color_name" = "$color_to_use" ] ; then
      outsvg=${outdir}/$(basename ${insvg} .svg)-${color_name}.svg
      sed s/"#000"/"${hex}"/g "${insvg}" > "${outsvg}"
    fi
  done
done
