#!/usr/bin/env bash
#
# Build other logos from a common svg source
#
set -euf -o pipefail

svg=$1
dir=$2
format=$3

heights=( 16 32 64 128 256 512)
for height in "${heights[@]}"
do
  path=${dir}/$(basename ${dir})-${height}.${format}
  rsvg-convert --keep-aspect-ratio --height ${height} --format ${format} --output ${path} ${svg}
done
