#!/usr/bin/env bash
#
# Build other logos from a common svg source
#
set -euf -o pipefail

# ./node_modules/.bin/svgo --disable=cleanupIDs src/cucumber-mark-tm.svg

# Primary colours from brand guide
ARRAY=( "red:#ff1245"
        "green:#00a818"
        "purple:#3e10af"
        "orange:#ff7f00"
        "yellow:#ffda00"
        "black:#1b1d1e"
      )

for svg in $(find src -name "*.svg"); do
  for color in "${ARRAY[@]}" ; do
    color_name="${color%%:*}"
    hex="${color##*:}"

    outsvg=build/$(basename ${svg} .svg)-${color_name}.svg
    sed s/#000/${hex}/ "${svg}" > "${outsvg}"
  done
done
