#!/usr/bin/env bash
#
# Build other logos from a common svg source
#
set -euf -o pipefail

#declare -A colours=( ["red"]="#ff1245" ["green"]="#00a818" ["purple"]="#3e10af" )

ARRAY=( "red:#ff1245"
        "green:#00a818"
        "purple:#3e10af" )

for color in "${ARRAY[@]}" ; do
    name="${color%%:*}"
    hex="${color##*:}"
    printf "%s is %s.\n" "$name" "$hex"
done
