#!/usr/bin/env bash
#
# Build other logos from a common svg source
#
set -euf -o pipefail

# Primary colours from brand guide
ARRAY=( "red:#ff1245"
        "green:#00a818"
        "purple:#3e10af"
        "orange:#ff7f00"
        "yellow:#ffda00"
        "black:#1b1d1e"
      )

for color in "${ARRAY[@]}" ; do
    name="${color%%:*}"
    hex="${color##*:}"
    sed s/#000000/${hex}/ src/cucumber-mark-bw.svg > build/cucumber-mark-${name}.svg
done
